# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'game2048.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 900)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/images/logo-2048.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(355, 242, 650, 650))
        self.frame.setStyleSheet("QFrame{\n"
"background:transparent;\n"
"border-image:url(:/resources/images/gridBackground.png);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(19, 19, 611, 621))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridBoard = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridBoard.setContentsMargins(6, 6, 6, 6)
        self.gridBoard.setObjectName("gridBoard")
        self.lbBackground = QtWidgets.QLabel(self.centralwidget)
        self.lbBackground.setGeometry(QtCore.QRect(0, -1, 1031, 901))
        self.lbBackground.setText("")
        self.lbBackground.setObjectName("lbBackground")
        self.bExit = QtWidgets.QPushButton(self.centralwidget)
        self.bExit.setGeometry(QtCore.QRect(51, 806, 221, 81))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(22)
        self.bExit.setFont(font)
        self.bExit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bExit.setStyleSheet("QPushButton{\n"
"background: rgb(255, 131, 69);\n"
"border: 6px solid rgb(255, 96, 99);\n"
"border-image:url(:/resources/images/btn.png);\n"
"border-radius: 18px\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(255, 131, 69);\n"
"border: 6px solid rgb(255, 96, 99);\n"
"border-image:url(:/resources/images/btn_pressed.png);\n"
"border-radius: 18px\n"
"}")
        self.bExit.setObjectName("bExit")
        self.lTopUi = QtWidgets.QLabel(self.centralwidget)
        self.lTopUi.setGeometry(QtCore.QRect(360, 20, 631, 141))
        self.lTopUi.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/TopUi.png)\n"
"}")
        self.lTopUi.setText("")
        self.lTopUi.setObjectName("lTopUi")
        self.sndslider = QtWidgets.QSlider(self.centralwidget)
        self.sndslider.setGeometry(QtCore.QRect(97, 575, 201, 20))
        self.sndslider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.sndslider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 24px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(202, 255, 158);\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(255, 107, 129)\n"
"}")
        self.sndslider.setOrientation(QtCore.Qt.Horizontal)
        self.sndslider.setObjectName("sndslider")
        self.musslider = QtWidgets.QSlider(self.centralwidget)
        self.musslider.setGeometry(QtCore.QRect(97, 495, 201, 51))
        self.musslider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.musslider.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 24px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: rgb(202, 255, 158);\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: rgb(255, 107, 129)\n"
"}")
        self.musslider.setOrientation(QtCore.Qt.Horizontal)
        self.musslider.setObjectName("musslider")
        self.lMusic = QtWidgets.QLabel(self.centralwidget)
        self.lMusic.setGeometry(QtCore.QRect(39, 498, 51, 51))
        self.lMusic.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/music_on.png)\n"
"}")
        self.lMusic.setText("")
        self.lMusic.setObjectName("lMusic")
        self.lSound = QtWidgets.QLabel(self.centralwidget)
        self.lSound.setGeometry(QtCore.QRect(39, 560, 51, 51))
        self.lSound.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/sound_on.png)\n"
"}")
        self.lSound.setText("")
        self.lSound.setObjectName("lSound")
        self.lScore = QtWidgets.QLabel(self.centralwidget)
        self.lScore.setGeometry(QtCore.QRect(380, 50, 181, 61))
        font = QtGui.QFont()
        font.setFamily("JACKPORT COLLEGE NCV")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lScore.setFont(font)
        self.lScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lScore.setObjectName("lScore")
        self.lHiScore = QtWidgets.QLabel(self.centralwidget)
        self.lHiScore.setGeometry(QtCore.QRect(790, 50, 181, 61))
        font = QtGui.QFont()
        font.setFamily("JACKPORT COLLEGE NCV")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lHiScore.setFont(font)
        self.lHiScore.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lHiScore.setObjectName("lHiScore")
        self.bPlay = QtWidgets.QPushButton(self.centralwidget)
        self.bPlay.setGeometry(QtCore.QRect(606, 18, 141, 131))
        self.bPlay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bPlay.setStyleSheet("QPushButton{\n"
"border-image: url(:/resources/images/bPlay.png)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-image: url(:/resources/images/bPlay_pressed.png)\n"
"}")
        self.bPlay.setText("")
        self.bPlay.setObjectName("bPlay")
        self.lLogo = QtWidgets.QLabel(self.centralwidget)
        self.lLogo.setGeometry(QtCore.QRect(5, -1, 301, 341))
        self.lLogo.setStyleSheet("QLabel{\n"
"border-image:url(:/resources/images/logo-2048.png)\n"
"}")
        self.lLogo.setText("")
        self.lLogo.setObjectName("lLogo")
        self.lMediaSet = QtWidgets.QLabel(self.centralwidget)
        self.lMediaSet.setGeometry(QtCore.QRect(40, 380, 271, 121))
        font = QtGui.QFont()
        font.setFamily("PF Scandal Pro Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.lMediaSet.setFont(font)
        self.lMediaSet.setStyleSheet("QLabel{\n"
"color: rgb(57, 0, 85)\n"
"}")
        self.lMediaSet.setAlignment(QtCore.Qt.AlignCenter)
        self.lMediaSet.setObjectName("lMediaSet")
        self.lBackOptions = QtWidgets.QLabel(self.centralwidget)
        self.lBackOptions.setGeometry(QtCore.QRect(27, 380, 301, 331))
        self.lBackOptions.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/gridBackground.png)\n"
"}")
        self.lBackOptions.setText("")
        self.lBackOptions.setObjectName("lBackOptions")
        self.lBest = QtWidgets.QLabel(self.centralwidget)
        self.lBest.setGeometry(QtCore.QRect(773, -1, 52, 61))
        self.lBest.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/best.png)\n"
"}")
        self.lBest.setText("")
        self.lBest.setObjectName("lBest")
        self.lCoins = QtWidgets.QLabel(self.centralwidget)
        self.lCoins.setGeometry(QtCore.QRect(370, 0, 52, 61))
        self.lCoins.setStyleSheet("QLabel{\n"
"border-image: url(:/resources/images/coins.png)\n"
"}")
        self.lCoins.setText("")
        self.lCoins.setObjectName("lCoins")
        self.bHelp = QtWidgets.QPushButton(self.centralwidget)
        self.bHelp.setGeometry(QtCore.QRect(130, 720, 71, 71))
        self.bHelp.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bHelp.setStyleSheet("QPushButton{\n"
"border-image: url(:/resources/images/help.png)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-image: url(:/resources/images/help_pressed.png)\n"
"}")
        self.bHelp.setText("")
        self.bHelp.setObjectName("bHelp")
        self.bAnim = QtWidgets.QPushButton(self.centralwidget)
        self.bAnim.setGeometry(QtCore.QRect(133, 627, 71, 71))
        self.bAnim.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bAnim.setStyleSheet("QPushButton{\n"
"border-image: url(:/resources/images/anim_on.png)\n"
"}\n"
"")
        self.bAnim.setText("")
        self.bAnim.setObjectName("bAnim")
        self.lbBackground.raise_()
        self.lBackOptions.raise_()
        self.frame.raise_()
        self.bExit.raise_()
        self.lTopUi.raise_()
        self.sndslider.raise_()
        self.musslider.raise_()
        self.lMusic.raise_()
        self.lSound.raise_()
        self.lScore.raise_()
        self.lHiScore.raise_()
        self.bPlay.raise_()
        self.lLogo.raise_()
        self.lMediaSet.raise_()
        self.lBest.raise_()
        self.lCoins.raise_()
        self.bHelp.raise_()
        self.bAnim.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "2048"))
        self.bExit.setText(_translate("MainWindow", "Εξοδος"))
        self.lScore.setText(_translate("MainWindow", "0"))
        self.lHiScore.setText(_translate("MainWindow", "0"))
        self.lMediaSet.setText(_translate("MainWindow", "ΡΥΘΜΙΣΕΙΣ"))
import resources
